# Configuration for Federated NER Experiments

model_name: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract

data:
data:
  pubtator_path: ./data_set/corpus_pubtator.txt               
  trng_pmids_path: ./data_set/corpus_pubtator_pmids_trng.txt   
  dev_pmids_path:   ./data_set/corpus_pubtator_pmids_dev.txt    
  test_pmids_path:  ./data_set/corpus_pubtator_pmids_test.txt   
  partition_strategy: "iid"     
  noniid_alpha: 0.5                

training:
  algorithm: FedAvg          # Options: FedAvg, FedAdam, FedKD, Centralized
  num_clients: 5
  rounds: 5
  local_epochs: 2

hyperparameters:
  learning_rate: 3e-5
  train_batch_size: 32
  eval_batch_size: 32
  max_seq_length: 128
  lr_scheduler_type: constant 
misc:
  seed: 42
  device: auto               # Options: auto, cpu, cuda
  save_results: true
